- name: FirstModel
  version: 0.3
  activate: true
  data:
    pipe:
      source: local
      args:
        file_path: 'D:\Tools\projects\bot\sanlap-core\resources\corpus.txt'
        delimiter: '\t'
    train_test_split_ratio: 0.30
    meta:
      label:
        - intent
      feature: question
  train:
    model:
      name: svm
  predict:
    path: 'D:\Users\Nikhil KM\Projects\sanlap\'